version: 0.2

phases:
 install:
  runtime-versions:
    nodejs: 16
  commands:
    - npm install

 build:
   commands:
     - echo Install application
     - npm run build

 post_build:
   commands:
     - echo Run test

artifacts:
  files:
    - 'dist/*'
  name: application-$(date +%Y-%m-%d)
