version: '2.2'

services:
    femodule:
      container_name: budgetcontrol-app
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - ./:/usr/src/app
      command: bash -c "npm install && build:tailwind && npm run serve"
      restart: unless-stopped
      networks:
        - services_budgetcontrol_network

networks:
  services_budgetcontrol_network:
    external: true