version: '2.2'

services:
    femodule:
      container_name: budgetcontrol-pwa
      build:
        context: .
        dockerfile: Dockerfile
      networks:
        - budgetcontrol_network  
      volumes:
          - ./:/app
          - /app/node_modules

networks:
  budgetcontrol_network:
    name: budgetcontrol_network
    external: true
