version: '2.2'

services:
    femodule:
      image: budgetcontrol-application:beta_v1
      container_name: budgetcontrol-app
      build:
        context: .
        dockerfile: Dockerfile.dev
      command: tail -F /var/www/error.log
