version: '3'

services:
    femodule:
      container_name: budgetcontrol-pwa
      image: mlabfactory/php8-apache:v1.2.3
      restart: unless-stopped
      networks:
        - budgetcontrol_network    
      command: tail -F /var/www/workdir/storage/logs/error.log  
    
networks:
  budgetcontrol_network:
    name: budgetcontrol_network
    external: true
