version: '3'

services:
    femodule:
      container_name: budgetcontrol-pwa
      build:
        context: .
        dockerfile: Dockerfile.apache
      image: budgetcontrol-pwa:apache
      volumes:
          - ./:/usr/src/app
      restart: unless-stopped
      networks:
        - budgetcontrol_network    
      command: tail -F /var/www/workdir/storage/logs/error.log  
    
networks:
  budgetcontrol_network:
    name: budgetcontrol_network
    external: true