version: '2.2'

services:
    femodule:
      ports:
        - 8080:8080
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - ./:/usr/src/app
          - ./.env:/usr/src/app/.env
      command: "npm run serve"
      restart: unless-stopped
networks: 
  default: 
    external: 
      name: budget-tracker-net