version: '2.2'

services:
    femodule:
      image: budgetcontrol-application:node-beta_v1
      container_name: budgetcontrol-app
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - ./:/usr/src/app
      command: bash -c "npm run build"
      restart: unless-stopped
      networks:
        - services_budgetcontrol_network      

networks:
  services_budgetcontrol_network:
    external: true