version: '3'

services:
    femodule:
      platform: linux/x86_64
      container_name: budgetcontrol-pwa
      build:
        context: .
        dockerfile: Dockerfile
      image: budgetcontrol-pwa:node
      networks:
        - budgetcontrol_network  
      volumes:
          - ./:/app
          - /app/node_modules

networks:
  budgetcontrol_network:
    name: budgetcontrol_network
    external: true
