name: Deploy application

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read


jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: prod
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Dependencies
          run: npm install

        - name: Build package
          env:
            VUE_APP_API_PATH_V2: https://dev.app.budgetcontrol.cloud
            VUE_APP_ANDORID_STORE_URL: https://play.google.com/store/apps/details?id=com.budgetcontrol
            VUE_APP_VERSION: ${{ github.run_number }}
          run: npm run build
        
        - name: deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              username: ${{ secrets.SFTP_USER }} 
              server: ${{ secrets.SFTP_HOST }} 
              ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
              password: ${{ secrets.SFTP_PASSWORD }} 
              local_path: './dist/*'
              remote_path: '/var/www/budgetcontrol/Pwa/dist'
              sftpArgs: '-o ConnectTimeout=5'

        - name: copy dist folder into container
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SFTP_HOST }}
            username: ${{ secrets.SFTP_USER }}
            password: ${{ secrets.SFTP_PASSWORD }}
            port: 22
            script: docker cp /var/www/budgetcontrol/Pwa/dist/. budgetcontrol-pwa:/var/www/workdir/dist/

        - name: Invalidate CloudFront
          uses: chetan/invalidate-cloudfront-action@v2
          env:
            DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
            PATHS: "/*.js /*.css /*.svg"
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
